jwt:
    secret: bcpsecret
    expiration: 43200
    get:
        token:
            uri: /authenticate
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/exchange
        username: root
    jackson:
        default-property-inclusion: NON_NULL
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
        show-sql: false
    main:
        allow-circular-references: true
